<?xml version="1.0" encoding="utf-8"?>
<Database Name="CosmoMonger" Class="CosmoMongerDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=CosmoMonger;Persist Security Info=True;User ID=CosmoUser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CosmoMongerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="BaseShip" Member="BaseShips">
    <Type Name="BaseShip">
      <Column Name="BaseShipId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Storage="_Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="BasePrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CargoSpace" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InitialJumpDriveId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InitialWeaponId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InitialShieldId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BaseShip_Ship" Member="Ships" ThisKey="BaseShipId" OtherKey="BaseShipId" Type="Ship" />
      <Association Name="BaseShip_SystemShip" Member="SystemShips" ThisKey="BaseShipId" OtherKey="BaseShipId" Type="SystemShip" />
      <Association Name="Weapon_BaseShip" Member="InitialWeapon" Storage="_Weapon" ThisKey="InitialWeaponId" OtherKey="WeaponId" Type="Weapon" IsForeignKey="true" />
      <Association Name="JumpDrive_BaseShip" Member="InitialJumpDrive" Storage="_JumpDrive" ThisKey="InitialJumpDriveId" OtherKey="JumpDriveId" Type="JumpDrive" IsForeignKey="true" />
      <Association Name="Shield_BaseShip" Member="InitialShield" Storage="_Shield" ThisKey="InitialShieldId" OtherKey="ShieldId" Type="Shield" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Weapon" Member="Weapons">
    <Type Name="Weapon">
      <Column Name="WeaponId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Power" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TurnCost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CargoCost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BasePrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Weapon_BaseShip" Member="BaseShips" ThisKey="WeaponId" OtherKey="InitialWeaponId" Type="BaseShip" />
      <Association Name="Weapon_Ship" Member="Ships" ThisKey="WeaponId" OtherKey="WeaponId" Type="Ship" />
      <Association Name="Weapon_SystemWeaponUpgrade" Member="SystemWeaponUpgrades" ThisKey="WeaponId" OtherKey="WeaponId" Type="SystemWeaponUpgrade" />
    </Type>
  </Table>
  <Table Name="BuddyList" Member="BuddyLists">
    <Type Name="BuddyList">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FriendId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_BuddyList" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="User_BuddyList1" Member="Friend" ThisKey="FriendId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Good" Member="Goods">
    <Type Name="Good">
      <Column Name="GoodId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="BasePrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Contraband" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TargetCount" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Association Name="Good_ShipGood" Member="ShipGoods" ThisKey="GoodId" OtherKey="GoodId" Type="ShipGood" />
      <Association Name="Good_SystemGood" Member="SystemGoods" ThisKey="GoodId" OtherKey="GoodId" Type="SystemGood" />
    </Type>
  </Table>
  <Table Name="IgnoreList" Member="IgnoreLists">
    <Type Name="IgnoreList">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AntiFriendId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_IgnoreList" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="User_IgnoreList1" Member="AntiFriend" ThisKey="AntiFriendId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Combat" Member="Combats">
    <Type Name="Combat">
      <Column Name="AttackerShipId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DefenderShipId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Turn" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TurnPointsLeft" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Surrender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="JettisonCargo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CombatId" Type="System.Int32" DbType="int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Storage="_Complete" Type="Combat.CombatStatus" DbType="int NOT NULL" CanBeNull="false" />
      <Association Name="Ship_Combat" Member="AttackerShip" Storage="_Ship" ThisKey="AttackerShipId" OtherKey="ShipId" Type="Ship" IsForeignKey="true" />
      <Association Name="Ship_Combat1" Member="DefenderShip" Storage="_Ship1" ThisKey="DefenderShipId" OtherKey="ShipId" Type="Ship" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="JumpDrive" Member="JumpDrives">
    <Type Name="JumpDrive">
      <Column Name="JumpDriveId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Speed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Range" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CargoCost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BasePrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="JumpDrive_BaseShip" Member="BaseShips" ThisKey="JumpDriveId" OtherKey="InitialJumpDriveId" Type="BaseShip" />
      <Association Name="JumpDrive_Ship" Member="Ships" ThisKey="JumpDriveId" OtherKey="JumpDriveId" Type="Ship" />
      <Association Name="JumpDrive_SystemJumpDriveUpgrade" Member="SystemJumpDriveUpgrades" ThisKey="JumpDriveId" OtherKey="JumpDriveId" Type="SystemJumpDriveUpgrade" />
    </Type>
  </Table>
  <Table Name="Message" Member="Messages">
    <Type Name="Message">
      <Column Name="MessageId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecipientUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Content" Modifier="Virtual" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" IsDelayLoaded="true" />
      <Column Name="Time" Modifier="Virtual" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Received" Storage="_Read" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Modifier="Virtual" Type="System.String" DbType="varchar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VisibleToRecipient" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="VisibleToSender" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Message" Member="RecipientUser" Storage="_User1" Modifier="Virtual" ThisKey="RecipientUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="User_Message1" Member="SenderUser" Modifier="Virtual" ThisKey="SenderUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Npc" Member="Npcs">
    <Type Name="Npc">
      <Column Name="NpcId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NpcTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="RaceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShipId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Credits" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Badness" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bounty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NextActionTime" Storage="_LastActionTime" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Association Name="NpcType_Npc" Member="NpcType" ThisKey="NpcTypeId" OtherKey="NpcTypeId" Type="NpcType" IsForeignKey="true" />
      <Association Name="Race_Npc" Member="Race" ThisKey="RaceId" OtherKey="RaceId" Type="Race" IsForeignKey="true" />
      <Association Name="Ship_Npc" Member="Ship" ThisKey="ShipId" OtherKey="ShipId" Type="Ship" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="NpcType" Member="NpcTypes">
    <Type Name="NpcType">
      <Column Name="NpcTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="NpcType_Npc" Member="Npcs" ThisKey="NpcTypeId" OtherKey="NpcTypeId" Type="Npc" />
    </Type>
  </Table>
  <Table Name="Player" Member="Players">
    <Type Name="Player">
      <Column Name="PlayerId" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Modifier="Virtual" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="RaceId" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Reputation" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShipId" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankCredits" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CashCredits" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimePlayed" Modifier="Virtual" Type="System.Double" DbType="float NOT NULL" CanBeNull="false" />
      <Column Name="LastPlayed" Modifier="Virtual" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NetWorth" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BountyTotal" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HighestBounty" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShipsDestroyed" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ForcedSurrenders" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ForcedFlees" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CargoLootedWorth" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShipsLost" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SurrenderCount" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FleeCount" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CargoLostWorth" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Alive" Modifier="Virtual" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Race_Player" Member="Race" ThisKey="RaceId" OtherKey="RaceId" Type="Race" IsForeignKey="true" />
      <Association Name="Ship_Player" Member="Ship" Modifier="Virtual" ThisKey="ShipId" OtherKey="ShipId" Type="Ship" IsForeignKey="true" />
      <Association Name="User_Player" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Race" Member="Races">
    <Type Name="Race">
      <Column Name="RaceId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Weapons" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shields" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Engine" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Accuracy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HomeSystemId" Storage="_HomeSystem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="varchar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="RacialEnemyId" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="RacialPreferenceId" Type="System.Int32" DbType="int NULL" CanBeNull="true" />
      <Association Name="Race_Npc" Member="Npcs" ThisKey="RaceId" OtherKey="RaceId" Type="Npc" />
      <Association Name="Race_Player" Member="Players" ThisKey="RaceId" OtherKey="RaceId" Type="Player" />
      <Association Name="Race_Race" Member="Races" ThisKey="RaceId" OtherKey="RacialEnemyId" Type="Race" />
      <Association Name="Race_Race1" Member="Races1" ThisKey="RaceId" OtherKey="RacialPreferenceId" Type="Race" />
      <Association Name="Race_CosmoSystem" Member="CosmoSystems" ThisKey="RaceId" OtherKey="RaceId" Type="CosmoSystem" />
      <Association Name="CosmoSystem_Race" Member="HomeSystem" Storage="_CosmoSystem" ThisKey="HomeSystemId" OtherKey="SystemId" Type="CosmoSystem" IsForeignKey="true" />
      <Association Name="Race_Race" Member="RacialEnemy" ThisKey="RacialEnemyId" OtherKey="RaceId" Type="Race" IsForeignKey="true" />
      <Association Name="Race_Race1" Member="RacialPreference" ThisKey="RacialPreferenceId" OtherKey="RaceId" Type="Race" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Shield" Member="Shields">
    <Type Name="Shield">
      <Column Name="ShieldId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Strength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BasePrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CargoCost" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Association Name="Shield_BaseShip" Member="BaseShips" ThisKey="ShieldId" OtherKey="InitialShieldId" Type="BaseShip" />
      <Association Name="Shield_Ship" Member="Ships" ThisKey="ShieldId" OtherKey="ShieldId" Type="Ship" />
      <Association Name="Shield_SystemShieldUpgrade" Member="SystemShieldUpgrades" ThisKey="ShieldId" OtherKey="ShieldId" Type="SystemShieldUpgrade" />
    </Type>
  </Table>
  <Table Name="Ship" Member="Ships">
    <Type Name="Ship">
      <Column Name="ShipId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BaseShipId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SystemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WeaponId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JumpDriveId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShieldId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DamageEngine" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DamageWeapon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DamageShield" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DamageHull" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetSystemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrentJumpDriveCharge" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TargetSystemArrivalTime" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Association Name="Ship_Combat" Member="CombatsAttacker" Storage="_InProgressCombats" ThisKey="ShipId" OtherKey="AttackerShipId" Type="Combat" />
      <Association Name="Ship_Combat1" Member="CombatsDefender" Storage="_InProgressCombats1" ThisKey="ShipId" OtherKey="DefenderShipId" Type="Combat" />
      <Association Name="Ship_Npc" Member="Npcs" ThisKey="ShipId" OtherKey="ShipId" Type="Npc" />
      <Association Name="Ship_Player" Member="Players" Modifier="Virtual" ThisKey="ShipId" OtherKey="ShipId" Type="Player" />
      <Association Name="Ship_ShipGood" Member="ShipGoods" ThisKey="ShipId" OtherKey="ShipId" Type="ShipGood" />
      <Association Name="BaseShip_Ship" Member="BaseShip" Modifier="Virtual" ThisKey="BaseShipId" OtherKey="BaseShipId" Type="BaseShip" IsForeignKey="true" />
      <Association Name="JumpDrive_Ship" Member="JumpDrive" Modifier="Virtual" ThisKey="JumpDriveId" OtherKey="JumpDriveId" Type="JumpDrive" IsForeignKey="true" />
      <Association Name="Shield_Ship" Member="Shield" ThisKey="ShieldId" OtherKey="ShieldId" Type="Shield" IsForeignKey="true" />
      <Association Name="Weapon_Ship" Member="Weapon" ThisKey="WeaponId" OtherKey="WeaponId" Type="Weapon" IsForeignKey="true" />
      <Association Name="CosmoSystem_Ship" Member="CosmoSystem" Modifier="Virtual" ThisKey="SystemId" OtherKey="SystemId" Type="CosmoSystem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ShipGood" Member="ShipGoods">
    <Type Name="ShipGood">
      <Column Name="ShipId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GoodId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Good_ShipGood" Member="Good" ThisKey="GoodId" OtherKey="GoodId" Type="Good" IsForeignKey="true" />
      <Association Name="Ship_ShipGood" Member="Ship" ThisKey="ShipId" OtherKey="ShipId" Type="Ship" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="System" Member="CosmoSystems">
    <Type Name="CosmoSystem">
      <Column Name="SystemId" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Modifier="Virtual" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PositionX" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PositionY" Modifier="Virtual" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HasBank" Modifier="Virtual" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RaceId" AutoSync="Never" Type="System.Int32" DbType="int NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="CosmoSystem_Race" Member="Races" ThisKey="SystemId" OtherKey="HomeSystemId" Type="Race" />
      <Association Name="CosmoSystem_Ship" Member="Ships" Modifier="Virtual" ThisKey="SystemId" OtherKey="SystemId" Type="Ship" />
      <Association Name="CosmoSystem_SystemGood" Member="SystemGoods" ThisKey="SystemId" OtherKey="SystemId" Type="SystemGood" />
      <Association Name="CosmoSystem_SystemJumpDriveUpgrade" Member="SystemJumpDriveUpgrades" ThisKey="SystemId" OtherKey="SystemId" Type="SystemJumpDriveUpgrade" />
      <Association Name="CosmoSystem_SystemShieldUpgrade" Member="SystemShieldUpgrades" ThisKey="SystemId" OtherKey="SystemId" Type="SystemShieldUpgrade" />
      <Association Name="CosmoSystem_SystemShip" Member="SystemShips" ThisKey="SystemId" OtherKey="SystemId" Type="SystemShip" />
      <Association Name="CosmoSystem_SystemWeaponUpgrade" Member="SystemWeaponUpgrades" ThisKey="SystemId" OtherKey="SystemId" Type="SystemWeaponUpgrade" />
      <Association Name="Race_CosmoSystem" Member="Race" ThisKey="RaceId" OtherKey="RaceId" Type="Race" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="SystemGood" Member="SystemGoods">
    <Type Name="SystemGood">
      <Column Name="SystemId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GoodId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriceMultiplier" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ProductionFactor" Type="System.Double" DbType="float NOT NULL" CanBeNull="false" />
      <Column Name="ConsumptionFactor" Type="System.Double" DbType="float NOT NULL" CanBeNull="false" />
      <Association Name="Good_SystemGood" Member="Good" ThisKey="GoodId" OtherKey="GoodId" Type="Good" IsForeignKey="true" />
      <Association Name="CosmoSystem_SystemGood" Member="CosmoSystem" ThisKey="SystemId" OtherKey="SystemId" Type="CosmoSystem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="SystemJumpDriveUpgrade" Member="SystemJumpDriveUpgrades">
    <Type Name="SystemJumpDriveUpgrade">
      <Column Name="SystemId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="JumpDriveId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriceMultiplier" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="JumpDrive_SystemJumpDriveUpgrade" Member="JumpDrive" Modifier="Virtual" ThisKey="JumpDriveId" OtherKey="JumpDriveId" Type="JumpDrive" IsForeignKey="true" />
      <Association Name="CosmoSystem_SystemJumpDriveUpgrade" Member="CosmoSystem" ThisKey="SystemId" OtherKey="SystemId" Type="CosmoSystem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="SystemShieldUpgrade" Member="SystemShieldUpgrades">
    <Type Name="SystemShieldUpgrade">
      <Column Name="SystemId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShieldId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriceMultiplier" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Shield_SystemShieldUpgrade" Member="Shield" ThisKey="ShieldId" OtherKey="ShieldId" Type="Shield" IsForeignKey="true" />
      <Association Name="CosmoSystem_SystemShieldUpgrade" Member="CosmoSystem" ThisKey="SystemId" OtherKey="SystemId" Type="CosmoSystem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="SystemShip" Member="SystemShips">
    <Type Name="SystemShip">
      <Column Name="SystemId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BaseShipId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriceMultiplier" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="BaseShip_SystemShip" Member="BaseShip" Modifier="Virtual" ThisKey="BaseShipId" OtherKey="BaseShipId" Type="BaseShip" IsForeignKey="true" />
      <Association Name="CosmoSystem_SystemShip" Member="CosmoSystem" ThisKey="SystemId" OtherKey="SystemId" Type="CosmoSystem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="SystemWeaponUpgrade" Member="SystemWeaponUpgrades">
    <Type Name="SystemWeaponUpgrade">
      <Column Name="SystemId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WeaponId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriceMultiplier" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="CosmoSystem_SystemWeaponUpgrade" Member="CosmoSystem" ThisKey="SystemId" OtherKey="SystemId" Type="CosmoSystem" IsForeignKey="true" />
      <Association Name="Weapon_SystemWeaponUpgrade" Member="Weapon" ThisKey="WeaponId" OtherKey="WeaponId" Type="Weapon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Modifier="Virtual" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Validated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Admin" Modifier="Virtual" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="LoginAttemptCount" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="LastActivity" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="LastVerificationSent" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="Joined" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Column Name="SessionID" Type="System.String" DbType="varchar(128)" CanBeNull="true" />
      <Association Name="User_BuddyList" Member="BuddyLists" ThisKey="UserId" OtherKey="UserId" Type="BuddyList" />
      <Association Name="User_BuddyList1" Member="BuddyListsOn" ThisKey="UserId" OtherKey="FriendId" Type="BuddyList" />
      <Association Name="User_IgnoreList" Member="IgnoreLists" ThisKey="UserId" OtherKey="UserId" Type="IgnoreList" />
      <Association Name="User_IgnoreList1" Member="IgnoreListsOn" ThisKey="UserId" OtherKey="AntiFriendId" Type="IgnoreList" />
      <Association Name="User_Message" Member="Messages" Storage="_Messages1" ThisKey="UserId" OtherKey="RecipientUserId" Type="Message" />
      <Association Name="User_Message1" Member="MessagesSent" ThisKey="UserId" OtherKey="SenderUserId" Type="Message" />
      <Association Name="User_Player" Member="Players" ThisKey="UserId" OtherKey="UserId" Type="Player" />
    </Type>
  </Table>
</Database>